import { motion, AnimatePresence } from "framer-motion";
import { Smartphone, ChevronRight } from "lucide-react";
import { Switch } from "../ui";

interface MfaStatusCardProps {
  enabled: boolean;
  onSetup: () => void;
  onDisable: () => void;
}

const MfaStatusCard = ({ enabled, onSetup, onDisable }: MfaStatusCardProps) => {
  return (
    <motion.div
      className="bg-white rounded-xl border border-grey-light overflow-hidden"
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
    >
      {/* Header */}
      <div className="flex items-center gap-3 px-5 py-4 sm:px-6 border-b border-grey-light bg-base-white">
        <div className="min-w-0 flex-1">
          <h3 className="body-bold-16 text-grey">
            Multi-Factor Authentication
          </h3>
          <p className="text-xs text-grey-medium mt-0.5">
            Add an extra layer of security to your account
          </p>
        </div>
      </div>

      {/* Toggle */}
      <div className="px-5 py-4 sm:px-6">
        <div className="flex items-center justify-between">
          <div className="min-w-0 flex-1 pr-4">
            <span className="body-bold-16 text-grey block">
              {enabled ? "MFA is enabled" : "Enable MFA"}
            </span>
            <p className="body-regular-16 text-grey-medium mt-1">
              {enabled
                ? "Your account is secured with an authenticator app."
                : "Require a verification code from an authenticator app every time you log in."}
            </p>
          </div>
          <Switch
            enabled={enabled}
            onChange={enabled ? onDisable : onSetup}
            aria-label={
              enabled
                ? "Disable multi-factor authentication"
                : "Enable multi-factor authentication"
            }
          />
        </div>
      </div>

      {/* Setup CTA (when OFF) */}
      <AnimatePresence>
        {!enabled && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.25 }}
          >
            <div className="px-5 pb-5 sm:px-6">
              <button
                type="button"
                onClick={onSetup}
                className="w-full group flex items-center gap-4 rounded-xl border-2 border-dashed border-grey-light bg-base-white p-4 sm:p-5 transition-all hover:border-primary hover:bg-primary-light/20 active:scale-[0.99]"
              >
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-primary-light transition-colors group-hover:bg-primary/10">
                  <Smartphone className="h-6 w-6 text-primary" />
                </div>
                <div className="min-w-0 flex-1 text-left">
                  <span className="body-bold-16 text-grey block">
                    Authenticator App
                  </span>
                  <span className="text-sm text-grey-medium block mt-0.5">
                    Use Google Authenticator, Microsoft Authenticator, or Authy
                    to generate verification codes.
                  </span>
                </div>
                <ChevronRight className="h-5 w-5 shrink-0 text-grey-medium transition-transform group-hover:translate-x-0.5 group-hover:text-primary" />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Active status (when ON) */}
      <AnimatePresence>
        {enabled && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.25 }}
          >
            <div className="px-5 pb-5 sm:px-6">
              <div className="flex items-center gap-4 rounded-xl border border-primary/20 bg-primary-light/30 p-4 sm:p-5">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-primary/10">
                  <Smartphone className="h-6 w-6 text-primary" />
                </div>
                <div className="min-w-0 flex-1">
                  <span className="body-bold-16 text-primary block">
                    Authenticator App
                  </span>
                  <span className="text-sm text-grey-medium block mt-0.5">
                    Verification codes are generated by your authenticator app.
                  </span>
                </div>
                <span className="hidden sm:inline-flex items-center gap-1.5 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
                  Active
                </span>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export default MfaStatusCard;
