import type { ContactRecord, ContactStatus } from "./types";

export const STATUS_STYLES: Record<
  ContactStatus,
  { label: string; bg: string; text: string; dot: string }
> = {
  active: {
    label: "Active",
    bg: "bg-success-light",
    text: "text-success",
    dot: "bg-success",
  },
  inactive: {
    label: "Inactive",
    bg: "bg-grey-light",
    text: "text-grey-medium",
    dot: "bg-grey-medium",
  },
  blocked: {
    label: "Blocked",
    bg: "bg-danger-light",
    text: "text-danger",
    dot: "bg-danger",
  },
};

export const CHANNEL_META: Record<string, { label: string; color: string }> = {
  WHATSAPP: { label: "WhatsApp", color: "#25D366" },
  FACEBOOK: { label: "Facebook", color: "#1877F2" },
  INSTAGRAM: { label: "Instagram", color: "#E1306C" },
  TIKTOK: { label: "TikTok", color: "#000000" },
};

export const MOCK_CONTACTS: ContactRecord[] = [
  {
    id: "c-001",
    name: "Aarav Sharma",
    email: "aarav.sharma@acmecorp.com",
    phone: "+91 98765 43210",
    company: "Acme Corp",
    channel: "WHATSAPP",
    status: "active",
    lastMessageAt: "2 min ago",
    conversationCount: 14,
    tags: ["VIP", "Enterprise"],
  },
  {
    id: "c-002",
    name: "Olivia Turner",
    email: "olivia.turner@northwind.io",
    phone: "+1 (415) 555-0192",
    company: "Northwind",
    channel: "FACEBOOK",
    status: "active",
    lastMessageAt: "15 min ago",
    conversationCount: 8,
    tags: ["Support"],
  },
  {
    id: "c-003",
    name: "Liam Chen",
    email: "liam.chen@globex.com",
    phone: "+1 (628) 555-0107",
    company: "Globex",
    channel: "INSTAGRAM",
    status: "inactive",
    lastMessageAt: "3 days ago",
    conversationCount: 3,
    tags: [],
  },
  {
    id: "c-004",
    name: "Fatima Noor",
    email: "fatima.noor@everline.ai",
    phone: "+971 50 123 4567",
    company: "Everline AI",
    channel: "WHATSAPP",
    status: "active",
    lastMessageAt: "1 hour ago",
    conversationCount: 22,
    tags: ["VIP"],
  },
  {
    id: "c-005",
    name: "Noah Williams",
    email: "noah.williams@zenroute.co",
    phone: "+44 20 7946 0958",
    company: "ZenRoute",
    channel: "TIKTOK",
    status: "inactive",
    lastMessageAt: "1 week ago",
    conversationCount: 1,
    tags: ["New"],
  },
  {
    id: "c-006",
    name: "Priya Patel",
    email: "priya.patel@dataflow.in",
    phone: "+91 88005 67890",
    company: "DataFlow",
    channel: "INSTAGRAM",
    status: "active",
    lastMessageAt: "30 min ago",
    conversationCount: 11,
    tags: ["Enterprise"],
  },
  {
    id: "c-007",
    name: "Carlos Mendez",
    email: "carlos@brightpath.mx",
    phone: "+52 55 1234 5678",
    company: "BrightPath",
    channel: "FACEBOOK",
    status: "blocked",
    lastMessageAt: "2 weeks ago",
    conversationCount: 5,
    tags: ["Flagged"],
  },
  {
    id: "c-008",
    name: "Emma Johansson",
    email: "emma.j@nordictech.se",
    phone: "+46 70 123 4567",
    company: "NordicTech",
    channel: "WHATSAPP",
    status: "active",
    lastMessageAt: "5 min ago",
    conversationCount: 19,
    tags: ["VIP", "Support"],
  },
];
