export const conversations = [
  {
    name: "Jerry Helfer",
    message: "Hey. What's the price of this?",
    time: "2:24 PM",
    avatar: "https://i.pravatar.cc/150?img=1",
    unread: true,
    platform: "whatsapp",
  },
  {
    name: "Jerry Helfer",
    message: "I loved your product.",
    time: "22/05/2024",
    avatar: "https://i.pravatar.cc/150?img=2",
    unread: false,
    platform: "facebook",
  },
  {
    name: "Jerry Helfer",
    message: "You: The price of the product yo...",
    time: "22/05/2024",
    avatar: "https://i.pravatar.cc/150?img=3",
    unread: false,
    platform: "instagram",
  },
  {
    name: "Samantha Lee",
    message: "Can you ship to Canada?",
    time: "10:15 AM",
    avatar: "https://i.pravatar.cc/150?img=4",
    unread: true,
    platform: "facebook",
  },
  {
    name: "Tom Reynolds",
    message: "Thanks! That really helped.",
    time: "Yesterday",
    avatar: "https://i.pravatar.cc/150?img=5",
    unread: false,
    platform: "whatsapp",
  },
  {
    name: "Angela Martin",
    message: "Is it available in black?",
    time: "06/06/2024",
    avatar: "https://i.pravatar.cc/150?img=6",
    unread: true,
    platform: "instagram",
  },
  {
    name: "David Kim",
    message: "You: Yes, we offer a 1-year warranty.",
    time: "06/06/2024",
    avatar: "https://i.pravatar.cc/150?img=7",
    unread: false,
    platform: "facebook",
  },
  {
    name: "Emily Clarke",
    message: "I'll place the order now.",
    time: "Today",
    avatar: "https://i.pravatar.cc/150?img=8",
    unread: true,
    platform: "whatsapp",
  },
  {
    name: "Mohit Sharma",
    message: "You: Let me check the stock...",
    time: "2 days ago",
    avatar: "https://i.pravatar.cc/150?img=9",
    unread: false,
    platform: "facebook",
  },
  {
    name: "Natalie Ross",
    message: "Can you provide bulk pricing?",
    time: "11:45 AM",
    avatar: "https://i.pravatar.cc/150?img=10",
    unread: true,
    platform: "facebook",
  },
  {
    name: "Carlos Mendez",
    message: "Where do you ship from?",
    time: "24/06/2024",
    avatar: "https://i.pravatar.cc/150?img=11",
    unread: false,
    platform: "whatsapp",
  },
  {
    name: "Liam O'Brien",
    message: "Do you offer same-day delivery?",
    time: "1 hour ago",
    avatar: "https://i.pravatar.cc/150?img=12",
    unread: true,
    platform: "instagram",
  },
  {
    name: "Mira Patel",
    message: "Thank you! Got the product.",
    time: "Yesterday",
    avatar: "https://i.pravatar.cc/150?img=13",
    unread: false,
    platform: "facebook",
  },
  {
    name: "Nathan Scott",
    message: "You: Sure, I can help with that.",
    time: "25/06/2024",
    avatar: "https://i.pravatar.cc/150?img=14",
    unread: false,
    platform: "whatsapp",
  },
  {
    name: "Ayesha Khan",
    message: "This looks awesome!",
    time: "Today",
    avatar: "https://i.pravatar.cc/150?img=15",
    unread: true,
    platform: "facebook",
  },
  {
    name: "Eric Johnson",
    message: "How do I return an item?",
    time: "3:30 PM",
    avatar: "https://i.pravatar.cc/150?img=16",
    unread: false,
    platform: "instagram",
  },
  {
    name: "Sophia Li",
    message: "You: No worries, I’ll guide you.",
    time: "1 minute ago",
    avatar: "https://i.pravatar.cc/150?img=17",
    unread: true,
    platform: "facebook",
  },
  {
    name: "Benito Cruz",
    message: "Received! Looks perfect.",
    time: "26/06/2024",
    avatar: "https://i.pravatar.cc/150?img=18",
    unread: false,
    platform: "whatsapp",
  },
];
