import type {
  TeamMember,
  ActivityEvent,
  TeamSummary,
  MemberStatus,
  ActivityAction,
} from "./types";

export const STATUS_CONFIG: Record<
  MemberStatus,
  { label: string; dot: string; bg: string; text: string }
> = {
  online: {
    label: "Online",
    dot: "bg-success",
    bg: "bg-success-light",
    text: "text-success",
  },
  away: {
    label: "Away",
    dot: "bg-warning",
    bg: "bg-warning-light",
    text: "text-warning-dark",
  },
  busy: {
    label: "Busy",
    dot: "bg-danger",
    bg: "bg-danger-light",
    text: "text-danger",
  },
  offline: {
    label: "Offline",
    dot: "bg-grey-medium",
    bg: "bg-grey-light",
    text: "text-grey-medium",
  },
};

export const ACTION_LABELS: Record<ActivityAction, string> = {
  replied: "replied to",
  resolved: "resolved",
  assigned: "assigned",
  tagged: "tagged in",
  transferred: "transferred",
  noted: "added a note to",
};

export const MOCK_MEMBERS: TeamMember[] = [
  {
    id: "m1",
    name: "Priya Sharma",
    email: "priya@chatblix.com",
    role: "Senior Agent",
    status: "online",
    activeMinutesToday: 342,
    activeConversations: 7,
    resolvedToday: 18,
    avgResponseTime: "1.2m",
    lastActiveAt: "Just now",
  },
  {
    id: "m2",
    name: "David Park",
    email: "david@chatblix.com",
    role: "Support Lead",
    status: "online",
    activeMinutesToday: 295,
    activeConversations: 4,
    resolvedToday: 12,
    avgResponseTime: "2.1m",
    lastActiveAt: "2 min ago",
  },
  {
    id: "m3",
    name: "Amara Okafor",
    email: "amara@chatblix.com",
    role: "Agent",
    status: "busy",
    activeMinutesToday: 180,
    activeConversations: 3,
    resolvedToday: 9,
    avgResponseTime: "3.5m",
    lastActiveAt: "5 min ago",
  },
  {
    id: "m4",
    name: "Lucas Meyer",
    email: "lucas@chatblix.com",
    role: "Agent",
    status: "away",
    activeMinutesToday: 120,
    activeConversations: 0,
    resolvedToday: 6,
    avgResponseTime: "4.0m",
    lastActiveAt: "18 min ago",
  },
  {
    id: "m5",
    name: "Sofia Reyes",
    email: "sofia@chatblix.com",
    role: "Junior Agent",
    status: "online",
    activeMinutesToday: 210,
    activeConversations: 5,
    resolvedToday: 8,
    avgResponseTime: "2.8m",
    lastActiveAt: "Just now",
  },
  {
    id: "m6",
    name: "Raj Patel",
    email: "raj@chatblix.com",
    role: "Agent",
    status: "offline",
    activeMinutesToday: 0,
    activeConversations: 0,
    resolvedToday: 0,
    avgResponseTime: "-",
    lastActiveAt: "3 hours ago",
  },
];

export const MOCK_ACTIVITY_FEED: ActivityEvent[] = [
  {
    id: "e1",
    memberId: "m1",
    memberName: "Priya Sharma",
    action: "resolved",
    target: "Order tracking issue #4521",
    channel: "WhatsApp",
    timestamp: "2 min ago",
  },
  {
    id: "e2",
    memberId: "m2",
    memberName: "David Park",
    action: "assigned",
    target: "Billing dispute #892",
    channel: "Email",
    timestamp: "5 min ago",
  },
  {
    id: "e3",
    memberId: "m5",
    memberName: "Sofia Reyes",
    action: "replied",
    target: "Product inquiry from Maria",
    channel: "Instagram",
    timestamp: "8 min ago",
  },
  {
    id: "e4",
    memberId: "m3",
    memberName: "Amara Okafor",
    action: "tagged",
    target: "Escalation: VIP account #201",
    channel: "Messenger",
    timestamp: "12 min ago",
  },
  {
    id: "e5",
    memberId: "m1",
    memberName: "Priya Sharma",
    action: "transferred",
    target: "Technical support request",
    channel: "WhatsApp",
    timestamp: "15 min ago",
  },
  {
    id: "e6",
    memberId: "m2",
    memberName: "David Park",
    action: "noted",
    target: "Follow-up needed: James R.",
    channel: "Email",
    timestamp: "22 min ago",
  },
];

export const MOCK_SUMMARY: TeamSummary = {
  totalMembers: 6,
  online: 3,
  away: 1,
  busy: 1,
  offline: 1,
  avgResponseTime: "2.7m",
  totalResolved: 53,
};
